In [1]:
import keras


Using TensorFlow backend.


In [21]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Activation
from keras import backend as K
import numpy as np

In [22]:
import pickle
f=open("trainX.pickle","rb")
images=pickle.load(f)
f=open("trainY.pickle","rb")
label=pickle.load(f)

In [109]:
img_r,img_c=28,28
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(images,label,test_size=0.2,random_state=1)

In [110]:
import pandas as pd
pd.DataFrame(y_train).describe()


0
count  48000.000000
mean       4.497521
std        2.871846
min        0.000000
25%        2.000000
50%        4.000000
75%        7.000000
max        9.000000

In [111]:
print(x_train.shape)

(48000, 28, 28)


In [112]:
print(y_train.shape)

(48000,)


In [113]:
K.image_data_format()

'channels_last'

In [146]:
batch_size=64
num_classes=10
epochs=10

In [115]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

x_train shape: (48000, 28, 28)
48000 train samples
12000 test samples


In [116]:
x_train = np.reshape(x_train, (48000, 784))
x_test = np.reshape(x_test, (12000, 784))

In [117]:
y_test.shape

(12000, 10)

In [134]:
model = Sequential()
model.add(Dense(800, input_dim=784) )
model.add(Activation('relu'))

model.add(Dense(500) )
model.add(Activation('relu'))

model.add(Dense(300))
model.add(Activation('relu'))

model.add(Dense(10))
model.add(Activation('softmax'))
model.summary()
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_92 (Dense)             (None, 800)               628000    
_________________________________________________________________
activation_83 (Activation)   (None, 800)               0         
_________________________________________________________________
dense_93 (Dense)             (None, 500)               400500    
_________________________________________________________________
activation_84 (Activation)   (None, 500)               0         
_________________________________________________________________
dense_94 (Dense)             (None, 300)               150300    
_________________________________________________________________
activation_85 (Activation)   (None, 300)               0         
_________________________________________________________________
dense_95 (Dense)             (None, 10)                3010      
__________

In [147]:
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 48000 samples, validate on 12000 samples
Epoch 1/10
48000/48000 [==============================] - 32s 668us/step - loss: 0.2456 - acc: 0.9062 - val_loss: 0.3085 - val_acc: 0.8928
Epoch 2/10
48000/48000 [==============================] - 30s 634us/step - loss: 0.2320 - acc: 0.9136 - val_loss: 0.3229 - val_acc: 0.8918
Epoch 3/10
48000/48000 [==============================] - 32s 668us/step - loss: 0.2211 - acc: 0.9158 - val_loss: 0.3123 - val_acc: 0.8920
Epoch 4/10
48000/48000 [==============================] - 30s 634us/step - loss: 0.2111 - acc: 0.9189 - val_loss: 0.3255 - val_acc: 0.8935
Epoch 5/10
48000/48000 [==============================] - 30s 634us/step - loss: 0.2026 - acc: 0.9222 - val_loss: 0.3866 - val_acc: 0.8756
Epoch 6/10
48000/48000 [==============================] - 30s 627us/step - loss: 0.1944 - acc: 0.9262 - val_loss: 0.4930 - val_acc: 0.8654
Epoch 7/10
48000/48000 [==============================] - 34s 713us/step - loss: 0.1881 - acc: 0.9281 - val_loss: 0.

In [106]:
y_test.shape

(12000, 10)

In [145]:
print(x_train.shape)

(48000, 784)


In [148]:
y_pred=model.predict(x_test)

In [167]:
y_pred[100].round(decimals=10)

array([1.712000e-07, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       1.370000e-08, 0.000000e+00, 1.408000e-07, 0.000000e+00,
       9.999997e-01, 0.000000e+00], dtype=float32)

In [165]:
y_pred[10]

array([3.5885103e-14, 4.9544862e-20, 1.0958191e-17, 1.8411712e-21,
       7.0825465e-16, 1.7605640e-18, 1.5282253e-14, 2.3762686e-16,
       1.0000000e+00, 4.6964853e-14], dtype=float32)

In [163]:
y_test[10]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)